Redefine context_data and worker_cls for ClusterRpcProxy + python3 support
clef/flask-nameko pull request #7
Opened 2017-01-13 09:19 UTC by scarchik

I has done some useful changes that need for my project and it will be great if I can commit it to your repository.

- Support Python 3 (python 3.5 tested, python2 support shouldn't be broken)
- Availability to redefine context_data and worker_cls  for ClusterRpcProxy
- Add common exception for flask_nameko

Sorry for so many changes in one pull request.

2017-01-13 19:03 UTC, jessepollak requested changes
This looks great to me — thank you for the PR! Two quick things:

1) Can you add a `six` dependency and use it in the place I mentioned to maintain compatibility with Python 2?
2) If possible, can you add Python 3.5 to tox so it can be tested?

Thanks again for the PR!

2017-01-13 19:03 UTC, jessepollak commented on flask_nameko/proxies.py
> +        for key, val in app.config.items():
Can we use `six.iteritems` here?

2017-01-14 17:01 UTC, scarchik commented on flask_nameko/proxies.py
> +        for key, val in app.config.items():
It looks unimportant: 
- this code use on application start only and shouldn't decrease performance
- config dictionary is not so big
- more one site-package dependency: **six**
If you disagree, I can add, what you think?

2017-01-20 17:22 UTC, jessepollak commented on flask_nameko/proxies.py
> +        for key, val in app.config.items():
I'm fine with that - thanks :)

2017-01-20 17:23 UTC, jessepollak commented
I'm fine with not including `six`, but can we add `3.5` to `tox`? Thanks!

2017-05-11 14:18 UTC, closed without merging